# Generated by Django 2.2 on 2020-01-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Youtube',
            new_name='Post',
        ),
    ]
